resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

variables:
  system.debug: 'true'

parameters:
- name: architectures
  type: object
  default:
  - name: AMD64
    value: amd64
    pool: pool-ubuntu-2004
  - name: ARM64
    value: arm64
    pool: ubuntu-arm64-2004-pool

jobs:
- job: CheckFilePermissions
  pool:
    name: ${{ variables.ubuntu_pool }}
  steps:
  - bash: |
      ls -l -R
      git config -l
      git config --system -l
      git config --global -l
