resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

variables:
- template: ${{ variables.Pipeline.Workspace }}/.azure-pipelines/templates/variables.yml

parameters:
- name: architectures
  type: object
  default:
  - name: AMD64
    value: amd64
    pool: pool-ubuntu-2004
  - name: ARM64
    value: arm64
    pool: ubuntu-arm64-2004-pool

jobs:
- job: CheckFilePermissions
  pool:
    name: ${{ variables.ubuntu_pool }}
  variables:
    system.debug: 'true'
  steps:
  - bash: |
      set -v
      ls -l -R
      git config -l
      git config --system -l
      git config --global -l
      getfacl src/azure-cli-core/azure/cli/core/__init__.py
      mount
