resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  branches:
    include:
    - '*'

jobs:
- job: TestWindowsMSI
  displayName: Test Windows MSI
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: PowerShell@2
    displayName: Install and Load CLI
    inputs:
      targetType: inline
      script: |
        Uninstall-Package -Name "Microsoft Azure CLI"
        $startTime = Get-Date
        $ProgressPreference = 'SilentlyContinue'; Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile .\AzureCLI.msi; Start-Process msiexec.exe -Wait -ArgumentList '/I AzureCLI.msi /quiet'; rm .\AzureCLI.msi
        $finishTime= Get-Date
        $totalTime = $finishTime - $startTime
        Write-Host "Total installation time is $($totalTime.Minutes) minutes, $($totalTime.Seconds) seconds"
